version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: meu_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: docker_dba
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
